rapid7/metasploitable3

Vagrantfile, scripts/installs/setup_apache_struts.bat, scripts/installs/setup_glassfish.bat, scripts/installs/setup_jenkins.bat, scripts/installs/start_glassfish_service.bat
Make sure that all services start on boot to ensure a consistent environment (until you break something by trying to exploit it 😄 ). Had to add GlassFish as a service instead of a scheduled task (which is how it should have been to start) to accommodate this.
To Verify:
=> Ensure all services start on reboot

Vagrantfile, resources/iis/applicationHost.config, scripts/installs/setup_ftp_site.bat, scripts/installs/setup_iis.bat
This PR adds FTP functionality to the existing IIS server. This FTP points to the inetpubroot folder for uploading new files accessible via IIS.
Verification:
=> Enable FTP on IIS for uploaded backdoors

Vagrantfile, scripts/installs/setup_axis2.bat
This adds the [Axis2 vulnerability](https://github.com/rapid7/metasploit-framework/pull/6457) for Metasploitable3
Verification
=> Add Axis2 vulnerability for Metasploitable3

Vagrantfile, resources/webdav/httpd-dav.conf, scripts/installs/setup_webdav.bat
This adds WebDAV to Metasploitable. The PR replaces #13.
Verification:
For exploitation:
=> Add WebDAV for Metasploitable3

Vagrantfile, scripts/configs/configure_firewall.bat, scripts/installs/setup_snmp.bat
=> Add SNMP for Metasploitable3

resources/wamp/phpmyadmin.conf
This makes PhpMyAdmin only locally accessible. However, if the server is compromised via another service, the attacker could create a pivot and connect to PhpMyAdmin anyway.
There is no MSF exploit for this PhpMyAdmin setup. If a pivot exists, the attacker can just connect to it with a browser.
Verification
=> Make PhpMyAdmin only locally accessible 

scripts/configs/create_users.bat
This hides all the users from the Windows welcome screen except for Vagrant.
Verification:
=> Hide users except Vagrant

scripts/installs/setup_glassfish.bat
GlassFish is running on a SYSTEM permission, which would make the box to easy.
Verification:
=> Update GlashFish service permission

scripts/configs/configure_firewall.bat
This updates the firewall rules for Metasploitable3 to make some services more difficult to access unless there is a pivot (or port-forwarding).
Verification:
* Port 135 TCP
* Port 139 TCP
* Port 445 TCP
* Port 3306 TCP
* Port 3389 TCP
* Port 5986 TCP
=> Update firewall rules to be more strict

answer_files/2008_r2/Autounattend.xml, build_win2008.ps1, build_win2008.sh
Increase the connection limits for WinRM to workaround a [Vagrant bug ](https://github.com/mitchellh/vagrant/issues/7489). This should be resolved with the next official release of Vagrant, but this workaround should help things work out of the box until then.
Verification
=> Increase base limits for WinRM connections

Vagrantfile
This sets up a private network between the host and the target VM, allowing you to scan and exploit the VM directly without needing any extra port forwards or network configuration.
=> add a private network for VM

Vagrantfile, scripts/configs/configure_firewall.bat, scripts/configs/disable_firewall.bat
This allows Metasploitable3 to have two levels of difficulty: easy and normal
- **Easy:** The firewall is off completely
- **Normal:** Only HTTP-based services (IIS, Apache, ManageEngine, GlassFish, etc) are not protected by the firewall, but they run on LOCAL SERVICE. The other higher privilege services are protected by the firewall.
Verification
=> Make difficulty configurable

build_win2008.sh
This relaxes the Vagrant check to only check OS X, since Linux works fine. It also checks for 'packer-io' first, since 'packer' is used by a differeht binary by default when the packer package is used on Arch linux.
This should continue working as expected on current platforms, but also work out of the box on current Arch Linux systems as well as others.
=> fix builds on Arch linux

scripts/installs/setup_glassfish.bat
This has proved very helpful when troubleshooting builds. Without it the second time this script runs it hangs waiting for input to 7zip like this:
```
default: Running: scripts/installs/install_boxstarter.bat as c:\tmp\vagrant-shell.bat
==> default: C:\Windows\system32>mkdir C:\glassfish 
==> default: 
==> default: A subdirectory or file C:\glassfish already exists.
==> default: 
==> default: C:\Windows\system32>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://download.java.net/glassfish/4.0/release/glassfish-4.0.zip', 'C:\Windows\Temp\glassfish4.zip')"  0<NUL 
==> default: C:\Windows\system32>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\glassfish4.zip" -oC:\glassfish" 
==> default: 
==> default: 7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor …
```
=> glassfish install: Enable overwriting in 7Zip

build_win2008.ps1
this is in response to issue #78 "build_win2008.ps1 Failing version check"
removed leading dash from exactMatch parameter call on line 37 of `build_win2008.ps1`
exactMatch sent the string "--exactMatch" to the CompareVersions function instead of $False, so the exactMatch if statement always executed in CompareVersions. Newer versions of VirtualBox would fail the version check
=> Fix VirtualBox version check in PowerShell build script

scripts/installs/install_elasticsearch.bat
Updated from 5 seconds to 30 seconds in order to accommodate different machine startup times. This is currently a quick fix. A more optimal solution may have to be researched. Refer to issue #63 for more details.
=> Updated the initial startup time for Elasticsearch

Vagrantfile, chef/cookbooks/metasploitable/files/unrealircd/unrealircd, chef/cookbooks/metasploitable/files/unrealircd/unrealircd.conf, chef/cookbooks/metasploitable/recipes/unrealircd.rb
This PR adds a new vulnerable service to the Linux VM, UnrealIRCd 3.2.8.1. This version was released with a backdoor used maliciously to access machines running the service.
Verification:
=> Add unrealircd Vulnerable Service

Vagrantfile, scripts/installs/setup_linux_share.bat
This adds a share that allows the attacker to upload malicious files onto the Linux machine.
Verification
=> Mount a share from Linux samba

build_win2008.ps1
Companion PR to #61, this one adds the enhanced VBox version checking messages to PowerShell build script for Windows users.  I verified it works-as-expected on a Windows 10 laptop at home.
An additional comment here: it'd probably be nice to add similar messages for the packer and vagrant version checking, as well (in both the PowerShell and bash build scripts).
The steps needed to make sure this thing works:
On a Windows system without VBox installed:
- **Verify** you see an error message that VBox doesn't appear to be installed and that the script stops
On a Windows system with an "old" (pre 5.1.0) version of VBox installed:
- **Verify** you see an error message that the version of VBox does not meet the minimum-required version and the script stops
On a Windows system with a "new …
=> Enhanced VBox version check error msgs for PS.

chef/cookbooks/metasploitable/files/apache/dav.conf, chef/cookbooks/metasploitable/recipes/apache.rb
This PR enables all necessary WebDAV modules for Apache and the appropriate configs to be able to upload files.
Verification (mostly stolen from [here](https://github.com/rapid7/metasploitable3/pull/16)):
For exploitation:
=> Enable WebDAV on Apache

Vagrantfile, chef/cookbooks/metasploitable/files/readme_app/readme_app, chef/cookbooks/metasploitable/files/readme_app/readme_app.conf, chef/cookbooks/metasploitable/files/readme_app/start.sh, chef/cookbooks/metasploitable/recipes/readme_app.rb, chef/cookbooks/metasploitable/recipes/ruby23.rb, chef/cookbooks/metasploitable/recipes/sinatra.rb
This PR adds a vulnerable Rails application. It contains information on the Metasploitable instance of your choice. It is vulnerable to RCE using the render function in ActionPack.
Verification
=> Add ReadMe Rails App

Vagrantfile, chef/cookbooks/metasploitable/files/cups/cupsd.conf, chef/cookbooks/metasploitable/recipes/cups.rb
This PR adds a vulnerable configuration of cups. It allows access on port 631 to the cups administration page and is exploitable using exploit/multi/http/cups_bash_env_exec.
Verification:
=> Add vulnerable service cups.

build_win2008.sh
Archlinux doesn't seem to use the option "DISTRIB_ID" in /etc/os-release anymore.
https://www.freedesktop.org/software/systemd/man/os-release.html lists no option as mandatory and ID seems like it could be stable.
Alternatively, /etc/arch-release might be around for a while and could be checked.
=> Fix Archlinux detection

Vagrantfile, chef/cookbooks/metasploitable/recipes/chatbot.rb, chef/cookbooks/metasploitable/recipes/nodejs.rb, chef/cookbooks/metasploitable/recipes/readme_app.rb, chef/cookbooks/metasploitable/recipes/sinatra.rb
This adds a vulnerability that allows CORS + command injection on a localhost service. It contains 3 components: a chatroom at metasploitable3ub/chat/, a chatroom client, and a features service for the bot that is meant for special features (in this case, looking up a system user)
=> Add chatbot to Linux VM

scripts/chocolatey_installs/tomcat.bat
This PR mentions the version of tomcat to be downloaded for smooth build. 
A general `choco install tomcat` downloads Apache Tomcat 8.5.12 by default. The service is installed with the name `Apache Tomcat 8.5 Tomcat8`.
But as per the [command provided in file `setup_apache_struts.bat`](https://github.com/rapid7/metasploitable3/blob/master/scripts/installs/setup_apache_struts.bat#L6), it starts the service: `net start "Apache Tomcat 8.0 Tomcat8"`
On using the version of tomcat, we could install the correct version.
**Checkout the next screenshots for more details:**
Error message during installation using `choco install tomcat`
**After installation of `choco install tomcat --version 8.0.33`**
Executing command `sc config Tomcat8 start= auto`
Executing command `net start "Apache Tomcat 8.0 …
=> Corrected tomcat version

scripts/installs/setup_apache_struts.bat
=> Fix typo in apache struct installer

scripts/installs/install_devkit.bat, windows_2008_r2.json
This PR resolves #179 and #180 - issue with ruby on rails application.
**Issue in detail:**
- Devkit installation created the folder `C:\Program Files\Rails_Server` ([Code](https://github.com/rapid7/metasploitable3/blob/master/scripts/installs/install_devkit.bat#L1))
- [Ruby on Rails initialization](https://github.com/rapid7/metasploitable3/blob/master/scripts/installs/install_rails_server.bat#L30) fails as the folder already exists
**Steps taken to resolve:**
- Moved Ruby DevKit installation to `C:\RubyDevKit` folder
**Verification:**
=> Moved devkit to RubyDevKit

scripts/installs/start_glassfish_service.bat
When requesting glassfish to start in vmware fusion 10 packer get
a non-zero exit code when service is already starting.  This looks
to be valid to simply ignore.
Testing requires a valid VMware Fusion 10 installation, virtualbox and VMware workstation/player should also be tested.
`packer build --only=vmware-iso windows_2008_r2.json`
=> suppress non-zero exit for glassfish start

build_win2008.ps1, build_win2008.sh
For build_win2008.ps1:
I made it to when you call packer it is a variable. The reason why I did that is because when you are installing packer on windows (at least for me) it just downloads the executable and you can put it anywhere. It isn't even called packer like how it is in your script (it is packer.exe), but I left it as packer in case of any formalities. So if you are on windows now you can just change the variable to whatever the location and name of your packer install is and it will get called in the script properly.
For  build_win2008.sh:
I just added antergos support by add the grep to do perl regex as well and the '|' means or (like normal) and that "antergos" is the id it is looking for. Currently works for antergos 17.9-ISO-Rolling.
=> Adding arch deviation support and packer var for windows.

scripts/installs/install_openjdk6.bat
Hello,
Proposed file change is potential fix for ""Could not create SSL/TLS secure channel"" with ""scripts/installs/install_openjdk6.bat"".
Discussed there: https://github.com/rapid7/metasploitable3/issues/219
Github.com [removed support for TLSv1/TLSv1.1](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/); PowerShell's default choice is TLSv1. By proposed changes - we will force PowerShell to use TLSv1.2.
- - - -
Also, I am not sure that it is a fix for entire https://github.com/rapid7/metasploitable3/issues/219 .
In addition, there (scripts/installs) are some other scripts with downloading files by PowerShell. Where "download.microsoft.com" in use; Not sure if they are planned to drop support for TLSv1. Maybe it may be good to tweak such places too.
Thanks!
=> Fix for "Could not create SSL/TLS secure channel".

packer/templates/windows_2008_r2.json
Locks version of chocolatey to fix failure to install when latest 0.10.9 is pulled down.
=> use chocolatey version 0.10.8 until install is fixed

packer/templates/ubuntu_1404.json
It was found that the latest version of chef-client (v14.0.190 released on 2018-04-03) had some issues with installing mysql service. I have hardcoded the version to be used : 13.8.5
My Packer version: v1.2.2
**Steps to test:**
(Merging this will fixes issues #262 and #263)
=> Hardcoded chef-client version to 13.8.5

packer/templates/ubuntu_1404.json
We don't need vm-tools, and the latest version of Virtualbox actually causes a kernel panic with our old kernel. This moves back to an older base, uses SHA256 to download it, and disables vm-tools.
Fixes #318
=> use an older base image, skip vm-tools

.gitignore, README.md, build.sh, packer/answer_files/2008_r2/Autounattend.xml, packer/scripts/virtio-win-drivers.sh, packer/templates/ubuntu_1404.json, packer/templates/windows_2008_r2.json
Reopened this pull request as the previous one was closed when I rebased.
I have implemented a script to pull the virtio drivers down as needed rather than checking them into the repo, as requested in #232 - I've also rebased against current master and reworked some portions of the build script to keep it DRY when dealing with multiple providers.
Other than those changes, these changes are the same as in #232
=> Added support for building and running on qemu/kvm via libvirt

README.md, build.sh
Fix #329, update `build.sh` to request the correct provider from the template for `libvirt` compatible systems.
=> updates for qemu as provider

build.sh
As noted in #342, detection for the vmware plugin is needed to have `build.sh` automatically generate vagrant boxes for vmware providers.
=> add detection for vmware provider plugin

packer/templates/windows_2008_r2.json, scripts/installs/vm-guest-tools.bat
fixes #216 
VMware tools requires the vcredist2008 installed and a reboot occur before installation on windows 2008r2.  This moves guest tools to install last just before cleanup.
Thanks to @jschulist for the report and @usmcfiredog for the additional validation that this issue persists.
=> make guest tools last so pre-reqs are in place

resources/rails_server/Gemfile
The new version of sqlite3 breaks the install process for the windows setup.
=> locking sqlite3 install version to 1.3.11

build.sh
The script will always create the box (using packer) even if it already exists.
=> Fix if then else statement

chef/cookbooks/metasploitable/recipes/knockd.rb, chef/cookbooks/metasploitable/recipes/proftpd.rb, chef/cookbooks/metasploitable/recipes/unrealircd.rb
`cookbook_file` + `source` on Windows copies files over using a windows terminal which adds carriage returns to EOL. Carriage returns on ubuntu prevent service start commands from functioning. Reports "file not found", breaking build.
Therefore, destroy all carriage returns. Wish I knew a more elegant way to do that besides `sed` after each affected file copy.
Closes #326 and friends
=> remove carriage returns from service config files

build.sh
There is a syntax error when running the script. Added the fix as stated in issue #339
=> added | tr -d ',' to resolve the syntax

scripts/installs/setup_glassfish.bat
Fix installing Glassfish on win2008. Issue [#411](https://github.com/rapid7/metasploitable3/issues/411)
=> Fix install Glassfish win2k8

scripts/installs/install_elasticsearch.bat
The install is failing as the .zip download was not working.  Updated link to elaticsearch.co, changed it from http to https, and updated the script to ignore cert errors.  All changes were required to make it work (for me at least).
=> Fix install of elasticsearch on Windows

packer/templates/windows_2008_r2.json, scripts/installs/install_chocolatey.ps1
When building the Windows 2008 Metasploitable3 machine, the installation always halts because it fails to download Chocolatey with an SSL/TLS error. Apparently, Powershell defaults to TLSv1.0 which isn't supported by the Chcolatey web server.
This fix instructs the net.webclient to use TLSv1.2, instead.
=> Fix Powershell SSL/TLS error for chocolatey download

scripts/chocolatey_installs/java.bat
The many services that rely on java need to have better limits.
By installing a specific compatible java version early the build
can eliminate churn and provide more consistent enviornments.
=> lock the java package

chef/cookbooks/metasploitable/recipes/clear_cache.rb
Safer, in case `/var/chef` does not exist
=> make clear_cache recipe idempotent

build.sh
`packer` build `provider` is not consistent at this time.
type qemu builder in the current packer config reports provider as `libvirt`
=> import libvirt box

packer/templates/vagrantfile-windows_2008_r2.template
Fixes #492 
The template file supplied inside the box images does not
have information about the external `name`, just reference config
and the provisioner type.
=> vagrant template should not reference `win2k8`

packer/templates/windows_2008_r2.json
The packer config for vmware-iso should not attempt tools install.
There is a provisioner script for tools install that detects the
environment and installer to use.
=> only use provisioner for tools

chef/cookbooks/metasploitable/recipes/iptables.rb
This is necessary because one of the last firewall rules otherwise drops all all incoming traffic for all interfaces. Prevents apache continuum's wrapper from connecting to the jvm or something like that, see https://github.com/rapid7/metasploitable3/pull/458#issuecomment-702942817
Also closes #458
=> allow all loopback traffic

chef/cookbooks/metasploitable/recipes/iptables.rb
Required for setup_linux_share.bat provisioning script on the windows
machine. Fix #393
Merges #394
=> Allow ICMP protocol for linux machine (merges #394)

scripts/installs/install_rails_server.bat
Rubygems.org has a new public certificate.
* disable cert validation for gem update --system
* restore checks for later bundle
resolves #499
=> Rubygems.org has a new public certificate.

packer/templates/windows_2008_r2.json, scripts/configs/vagrant-ssh.bat, scripts/configs/vagrant-ssh.ps1, scripts/installs/chocolatey.ps1, scripts/installs/install_chocolatey.ps1, scripts/installs/install_netfx40.ps1, scripts/installs/install_rails_server.bat, scripts/installs/setup_rails_server.bat
Fix #503 
As the internet tries to become more secure new challenges to creating intentionally insecure systems occur.
This uses an old trick from @jstangroome to enable Tls 1.2 usage for powershell downloads.
https://blog.stangroome.com/2011/03/23/executing-individual-powershell-commands-using-net-4/
https://gist.github.com/jstangroome/882528/9e0c55253a261a9c30d0d92cafba57ccbc8e4090
An added bonus in removal of some unused scripts.
=> enable tls12 for vagrant key download

scripts/installs/install_elasticsearch.bat
The original endpoint on http now returns a 302 that powershell does not follow.
=> download elasticsearch with https

scripts/installs/install_rails_server.bat
Recent changes to how rubygems and bundler are shipped require setting the build to use a specific version for rubygems during the rails setup process.
=> lock gem version for rails build

chef/cookbooks/metasploitable/recipes/nodejs.rb
```
virtualbox-iso: STDERR: E: There are problems and -y was used without --force-yes
virtualbox-iso: ---- End output of ["apt-get", "-q", "-y", "install", "nodejs=4.9.1-1nodesource1"] ----
virtualbox-iso: Ran ["apt-get", "-q", "-y", "install", "nodejs=4.9.1-1nodesource1"] returned 100
virtualbox-iso: [2021-03-28T06:54:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
virtualbox-iso: [2021-03-28T06:54:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
This error is also present when building the vmware box for Ubuntu 14.04.
Fix from @russdan on https://github.com/rapid7/metasploitable3/issues/515
=> Patch recipe NodeJS

scripts/installs/install_devkit.bat
Fix #529
The CDN previously used has shutdown.  Pull the devkit from metasploit build cache repo.
=> update devkit link to a git permalink

README.md, chef/dev/ub1404/Vagrantfile
* reference a new box that supports libvirt
* default-disable nfs and instead give instructions for using rsync for 
provisioning with chef-solo
=> update docs for using vagrant to develop ub1404

scripts/installs/install_manageengine.bat
This fix suggested by @nem0n in #438
Ensures ManageEngine install is parsed accurately
=> guard token in ManageEngine install
